Document: box2d
Title: Debian box2d Manual
Author: <insert document author here>
Abstract: This manual describes what box2d is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/box2d/box2d.sgml.gz

Format: postscript
Files: /usr/share/doc/box2d/box2d.ps.gz

Format: text
Files: /usr/share/doc/box2d/box2d.text.gz

Format: HTML
Index: /usr/share/doc/box2d/html/index.html
Files: /usr/share/doc/box2d/html/*.html
